options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Steps to pull a docker image for pgadmin, push it to container registry and deploy it to cloud run.
- name: "gcr.io/cloud-builders/docker"
  args: ['pull', 'dpage/pgadmin4']
- name: "gcr.io/cloud-builders/docker"
  args: ['tag', 'dpage/pgadmin4','gcr.io/msds432-wk9-2/pgadmin']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/msds432-wk9-2/pgadmin']
  
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy','pg-admin', '--image','gcr.io/msds432-wk9-2/pgadmin', '--region','us-central1', '--add-cloudsql-instances', 'msds432-wk9-2:us-central1:mypostgres','--platform','managed', '--port','80', '--allow-unauthenticated','--set-env-vars','PGADMIN_DEFAULT_EMAIL=kennagarcia09@gmail.com','--set-env-vars','PGADMIN_DEFAULT_PASSWORD=SuperSecret']
  
# Steps to build a docker image for go-microservice, push it to container registry and deploy it to cloud run.  
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/msds432-wk9-2/go-microservice','.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/msds432-wk9-2/go-microservice']
  
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy','go-microservice', '--image','gcr.io/msds432-wk9-2/go-microservice', '--region','us-central1', '--add-cloudsql-instances', 'msds432-wk9-2:us-central1:mypostgres','--platform','managed', '--port','8080', '--allow-unauthenticated']

# Steps to build a docker image for node.js app, push it to container registry, and deploy it to cloud run.
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/msds432-wk9-2/nodejs-app', '-f', 'Dockerfile.node', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/msds432-wk9-2/nodejs-app']

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy', 'nodejs-app', '--image', 'gcr.io/msds432-wk9-2/nodejs-app', '--region', 'us-central1', '--platform', 'managed', '--port', '8081', '--allow-unauthenticated']

images:
- gcr.io/msds432-wk9-2/go-microservice
- gcr.io/msds432-wk9-2/pgadmin
- gcr.io/msds432-wk9-2/nodejs-app
