options:
  logging: CLOUD_LOGGING_ONLY

# steps:
# # Steps to pull a docker image for pgadmin, push it to container registry and deploy it to cloud run.
# - name: "gcr.io/cloud-builders/docker"
#   args: ['pull', 'dpage/pgadmin4']
# - name: "gcr.io/cloud-builders/docker"
#   args: ['tag', 'dpage/pgadmin4','gcr.io/msds432-wk9-2/pgadmin']
# - name: "gcr.io/cloud-builders/docker"
#   args: ['push', 'gcr.io/msds432-wk9-2/pgadmin']
  
# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#   entrypoint: gcloud
#   args: ['run', 'deploy','pg-admin', '--image','gcr.io/msds432-wk9-2/pgadmin', '--region','us-central1', '--add-cloudsql-instances', 'ADD_YOUR_GCP_PROJECT_ID_HERE:us-central1:mypostgres','--platform','managed', '--port','80', '--allow-unauthenticated','--set-env-vars','PGADMIN_DEFAULT_EMAIL=user@gmail.com','--set-env-vars','PGADMIN_DEFAULT_PASSWORD=SuperSecret']
  
# # Steps to build a docker image for go-microservice, push it to container registry and deploy it to cloud run.  
# - name: "gcr.io/cloud-builders/docker"
#   args: ['build', '-t', 'gcr.io/msds432-wk9-2/go-microservice','.']
# - name: "gcr.io/cloud-builders/docker"
#   args: ['push', 'gcr.io/msds432-wk9-2/go-microservice']
  
# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#   entrypoint: gcloud
#   args: ['run', 'deploy','go-microservice', '--image','gcr.io/msds432-wk9-2/go-microservice', '--region','us-central1', '--add-cloudsql-instances', 'ADD_YOUR_GCP_PROJECT_ID_HERE:us-central1:mypostgres','--platform','managed', '--port','8080', '--allow-unauthenticated']
# images:
# - gcr.io/msds432-wk9-2/go-microservice
# - gcr.io/msds432-wk9-2/pgadmin



steps:
# Pull the pgadmin image from Docker Hub
- name: "gcr.io/cloud-builders/docker"
  args: ['pull', 'dpage/pgadmin4']

# Tag the image to match your Artifact Registry repository
- name: "gcr.io/cloud-builders/docker"
  args: ['tag', 'dpage/pgadmin4', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/pgadmin']

# Push the image to your Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/pgadmin']

# Deploy the pgadmin image to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy', 'pg-admin', '--image', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/pgadmin', '--region', 'us-central1', '--platform', 'managed', '--port', '80', '--allow-unauthenticated']

# Build and push your microservice Docker image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/go-microservice', '.']

- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/go-microservice']

# Deploy the microservice image to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy', 'go-microservice', '--image', 'us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/go-microservice', '--region', 'us-central1', '--platform', 'managed', '--port', '8080', '--allow-unauthenticated']

images:
  - us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/go-microservice
  - us-central1-docker.pkg.dev/msds432-wk9-2/gcr-repo/pgadmin
